/* Copyright (c) 2018 Stanford University
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <string>

#include "RAMCloudLogs.h"

/**
 * The static portion of all the logs in RAMCloud
 */
std::string RAMCloudLogs[] = {
    " -- %.2f%% done\n",
    "%.*s\n",
    "%8.1f ns (+%6.1f ns): %s\n",
    "%d inserts took %.2f seconds (%.2f Mobjects/sec)\n",
    "%d inserts took %lu ticks\n",
    "%d writes took %lu ticks\n",
    "%lu Misses / %lu Total -- %lu/%lu R/W\n",
    "%lu misses (+%lu misses): %s\n",
    "%lu recoveries blocked waiting for other recoveries\n",
    "%s SpinLock locked for one second; deadlock?\n",
    "%s exception thrown after reply sent for %s RPC\n",
    "%s has table %lu\n",
    "%s hasn't quiesced replication operations yet\n",
    "%s hasn't started backup recovery yet\n",
    "%s invoked before initialization complete; returning STATUS_RETRY\n",
    "%s%s\n",
    "%s: %s\n",
    "%s: Listening on %s\n",
    "%s: throughput: %.1f reads/sec., max latency: %.1fus, reads > 20us: %.1f%%\n",
    "%s: value = %.*s, key1 = %.*s, key2 = %.*s\n",
    "%s\n",
    "%s\n\n",
    "%u receive buffers now in use (%.1f%%)\n",
    "%u segments in the digest but not available from backups\n",
    "- quiescing writes\n",
    "<%s,%lu> recovery segments took %lu ms to construct, notifying other threads\n",
    "=================== NEW LEVEL (%u) ====================\n",
    "@%7lu: Got getRecoveryData response from %s, took %.1f us on channel %ld\n",
    "@%7lu: Replaying segment %lu done\n",
    "@%7lu: Replaying segment %lu with length %u\n",
    "@%7lu: Replica <%s,%lu,%lu> write -> %7u+%7u %u rpcs out %s\n",
    "@%7lu: Replica <%s,%lu,%lu> write -> %7u+%7u %u rpcs out OPEN\n",
    "@%7lu: Replica <%s,%lu,%lu> write <- %7u %u rpcs out %s\n",
    "@%7lu: Segment <%s,%lu> close queued\n",
    "@%7lu: Segment <%s,%lu> open queued\n",
    "A partial UpdateServerList request is detected. Perhaps limit the number of ProtoBufs the CoordinatorServerList can batch into one rpc.\n",
    "A recovery master failed to recover its partition\n",
    "ALL_DATA request from %s too short (got %u bytes, expected %u)\n",
    "ALL_DATA response from %s too short (got %u bytes, expected %u)\n",
    "Aborting %lu uncommitted segment(s)\n",
    "Aborting %s after %d ms (server not responding)\n",
    "Actual OPS %.0f / Target OPS %lu\n",
    "Adding %lu segment replicas from %s with bench speed of %lu\n",
    "Adding indexlet in tableId %lu indexId %u, but already own.\n",
    "All children done, Main thread exiting\n\n",
    "All slaves are done.\n",
    "Allocating new replicated segment for <%s,%lu>\n",
    "Allocating overflow bucket %d for index %lu\n",
    "Allocating overflow cache line %d for index %lu\n",
    "Already have given indexlet in indexId %u for tableId %lu, cannot add.\n",
    "Already have tablet [0x%lx,0x%lx] in tableId %lu, cannot add [0x%lx,0x%lx]\n",
    "An unhandled C++ Exception occurred: %s\n",
    "An unknown, unhandled C++ Exception occurred\n",
    "Asked for a recovery segment for segment <%s,%lu> which isn't part of this recovery\n",
    "Asked for partition %d from segment <%s,%lu> but there are only %d partitions\n",
    "Asked for recovery segment for <%s,%lu> but the master wasn't under recovery on the backup\n",
    "Asking recovery master to abort its recovery\n",
    "Assertion `%s' failed at %s:%u in %s\n",
    "Assigning table id %lu index id %u, to master %s\n",
    "Assigning table id %lu, key hashes 0x%lx-0x%lx, to master %s\n",
    "Attempted to get a child at an index larger than slotuse\n",
    "Average latency (object size %d, key size %u): %.1fus (%s)\n",
    "Average latency: %.1fus\n",
    "Backtrace:\n",
    "Backup %s has %lu segment replicas\n",
    "Backup %s no longer in cluster, trying next backup for segment %lu\n",
    "Backup %s returned a log digest for segment id/epoch <%lu, %lu> but the minimum <id, epoch> for this master is <%lu, %lu> so discarding it\n",
    "Backup %s started partitioning replicas\n",
    "Backup %s will store replicas under cluster name '%s'\n",
    "Backup at id %s has %u MB/s read\n",
    "Backup couldn't find existing superblock; starting as fresh backup.\n",
    "Backup is waiting for dirty write buffers to sync\n",
    "Backup preparing for recovery %lu of crashed server %s; loading %lu primary replicas\n",
    "Backup service started\n",
    "Backup storage opened with %lu bytes available; allocated %lu frame(s) across %lu file(s) with %lu bytes per frame\n",
    "Backup storage speeds (avg): %u MB/s read,\n",
    "Backup storage speeds (min): %u MB/s read\n",
    "Backup storing replicas with clusterName '%s'. Future backups must be restarted with the same clusterName for replicas stored on this backup to be reused.\n",
    "Backup write RPC for segment %lu rejected by %s with status %s\n",
    "Backup write RPC rejected by %s with STATUS_CALLER_NOT_IN_CLUSTER\n",
    "BackupSelector could not find a suitable server in %d attempts; may need to wait for additional servers to enlist\n",
    "BackupSelector could not find a suitable server in the last 20ms; seems to be stuck; waiting for the coordinator to notify this master of newly enlisted backups\n",
    "Bad BackupStrategy selected\n",
    "Bad BasicTransport gbs option value '%s' (expected positive integer); ignoring option\n",
    "Bad BasicTransport rttMicros option value '%s' (expected positive integer); ignoring option\n",
    "Bad fragment pointer: %p\n",
    "Bad log module level format: %s, example moduleName=3\n",
    "Bad object size (tbl %lu, obj %.*s)\n",
    "Bandwidth (%u-byte object with %u-byte key): %.1f MB/sec\n",
    "BasicTransport parameters: maxDataPerPacket %u, roundTripBytes %u, grantIncrement %u, pingIntervals %d, timeoutIntervals %d, timerInterval %.2f ms\n",
    "Became leader (no existing leader)\n",
    "Became leader with version %u (old leader info was \"%.*s\")\n",
    "Blocked waiting for lease to renew.\n",
    "Bookeeping issue detected; server's count of numUpdatingServers just went negative. Not total failure but will cause the updater thread to spin even w/o work. Cause is mismatch # of getWork() and workSuccess/Failed()\n",
    "Broadcasting the end of recovery %lu for server %s to backups\n",
    "Called by masterId %s with %u tablets and %u indexlets\n",
    "Can't destroy ObjectManager with active TombstoneProtectors.\n",
    "Can't open socket for doing IO control.\n",
    "Can't perform ioctl on kernel's ARP Cache for host at %s!\n",
    "Can't specify both -B and -M options\n",
    "Cannot find index '%u' for table '%lu'\n",
    "Cannot find table '%lu'\n",
    "Cannot partition segments from master %s since they have not been read yet (no preceeding startReadingDataRpc call)\n",
    "Cannot reassign tablet [0x%lx,0x%lx] in tableId %lu to %s: server not up\n",
    "Cannot use the fillWithTestData rpc since overwrite multiple times on same key is requested.\n",
    "Cant read NodeId %lu\n",
    "Changing state of this indexlet from %d to %d.\n",
    "Checking %s off the list for %lu\n",
    "Checking for Split tablets\n",
    "Checking for created tables\n\n",
    "Checking for dropped tables\n\n",
    "Checking inner node entry %s.\n",
    "Checking leaf node entry %s.\n",
    "Checking server id %s (%s)\n",
    "Chose server %s with %u primary replicas and %u MB/s disk bandwidth (expected time to read on recovery is %u ms)\n",
    "Cleaner finished syncing survivor segments: %.1f ms, %.1f MB/sec\n",
    "Cleaning used %u seglets to free %u seglets\n",
    "Client %d couldn't read from table %s\n",
    "Client %d got exception reading from table %s: %s\n",
    "Client %d got unknown exception reading from table %s\n",
    "Client %d reading from table %lu\n",
    "Client Stopped\n",
    "Client received LOG_TIME_TRACE request from server %s for (unknown) sequence %lu\n",
    "Client received LOG_TIME_TRACE request from server %s for sequence %lu\n",
    "Client:%d %s: hash throughput: %.1f hashes/sec, Lookup throughput: %.1f lookups/sec with an average rpc latency of %.2lfus\n",
    "Close server port %s after %d ms (listening timeout)\n",
    "Closing <%s,%lu>\n",
    "Closing session with %s (client port %d)\n",
    "Cluster '__unnamed__'; ignoring existing backup storage. Any replicas stored will not be reusable by future backups. Specify clusterName for persistence across backup restarts.\n",
    "Cluster name is '%s', external storage workspace is '%s'\n",
    "Command line: %s\n",
    "Commit() returned. %zu objs selected. Outcome:%d\n\n",
    "Committing the SideLog...\n",
    "Compaction used %u seglets to free %u seglets\n",
    "Comparing keys: %s vs %s\n",
    "Consistency error between event (server %s, status %s) and slot (server %s, status %s)\n",
    "Constructing an object of class ObjectRemove\n",
    "Constructing an object of class ObjectWrite\n",
    "Coordinator process id: %u\n",
    "Coordinator state has been recovered from external storage; starting service\n",
    "Coordinator tableManager after recovery master %s finished: %s\n",
    "CoordinatorServerList recovery completed: %u master(s), %u backup(s), %lu update(s) to disseminate, server list version is %lu\n",
    "CoordinatorServerList's  maxConfirmedVersion %lu is larger than its current version %lu. This should NEVER happen!\n",
    "Could not append ParticipantList! (leaseId: %lu, txId: %lu)\n",
    "Could not find tablet in tableId %lu with startKeyHash %lu and endKeyHash %lu: overlaps with one or more other ranges\n",
    "Could not find tablet in tableId %lu with startKeyHash %lu and endKeyHash %lu\n",
    "Could not lock all memory pages (%s), so the OS might swap memory later. Check your user's \"ulimit -l\" and adjust /etc/security/limits.conf as necessary.\n",
    "Could not open connection to LogCabin: support for LogCabin was disabled at compile time\n",
    "Could not open infiniband device list\n",
    "Could not reassign tablet [0x%lx,0x%lx] in tableId %lu: table not found\n",
    "Could not reassign tablet [0x%lx,0x%lx] in tableId %lu: tablet not found\n",
    "Could not recover transaction <%lu, %lu>; found prepared operation %lu for tableId:%lu keyHash:%lu but was unable to recover a transaction decision.\n",
    "Could not split table %lu at key hash %lu:no such tablet on this master\n",
    "Could not take ownership of tablet [0x%lx,0x%lx] in tableId %lu: overlaps with one or more different ranges.\n",
    "Couldn't allocate segment for cleaning\n",
    "Couldn't build recovery segments for <%s,%lu>: %s\n",
    "Couldn't close backup log\n",
    "Couldn't contact %s; server no longer in server list\n",
    "Couldn't contact server %s to start recovery: %s\n",
    "Couldn't create FileLogger for %s\n",
    "Couldn't find enough masters not already performing a recovery to recover all partitions: %u partitions will be recovered later\n",
    "Couldn't find service locator string in script startserver.py\n",
    "Couldn't find specified indexlet in table id %lu, index id %u\n",
    "Couldn't find tablet containing key hash 0x%lx in table '%s' (id %lu)\n",
    "Couldn't find value just written!\n",
    "Couldn't fit segment.\n",
    "Couldn't mmap gigabyte-aligned region\n",
    "Couldn't open ../scripts/startserver.py: %s\n",
    "Couldn't open /proc/self/statm: %s\n",
    "Couldn't open ZooKeeper connection: %s\n",
    "Couldn't open session for locator %s (%s)\n",
    "Couldn't parse contents of /proc/self/statm: %s\n",
    "Couldn't post Infiniband receive buffer: %s\n",
    "Couldn't read coordinator object for cluster %s from storage at '%s'\n",
    "Couldn't read superblock from superblock frame %u: %s\n",
    "Couldn't read superblock from superblock frame %u: read was short (read %ld bytes of %u)\n",
    "Couldn't recover ClientLease because lease object name '%s' is not an integer\n",
    "Couldn't register Infiniband memory region: %s\n",
    "Couldn't set signal handler for SIGSEGV, oh well\n",
    "Couldn't write to backup %s; server is down\n",
    "Counter %s overflowed on server %s, dropping an interval.\n\n",
    "Crashed master %s had %s %s replica for segment %lu\n",
    "Created %d tables, dropped %d tables, wrote %d objects, split %d tablets\n",
    "Created index 1\n",
    "Created index 2\n",
    "Created table\n",
    "Created zero-copy region with %lu bytes at %p\n",
    "Creating index '%u' for table '%lu'\n",
    "Creating table '%s' with id %lu\n",
    "Cycles::init couldn't read clock: %s\n",
    "Deadline invocation of checkTimeouts\n",
    "Deferring because <%s,%lu> not yet filtered\n",
    "Delaying open for segment %lu, replica %lu: too many RPCs in flight\n",
    "Delaying start of recovery of server %s; another recovery is active for the same ServerId\n",
    "Delaying write to segment %lu, replica %lu: too many RPCs in flight\n",
    "Destruct unknown multi-op object\n",
    "Destructor called before all seglets freed!\n",
    "DispatchExec::sync has been stalled for %.2f seconds\n",
    "Doing consistency check\n",
    "Done building recovery segments for (<%s,%lu>)\n",
    "Done writing objects.\n",
    "Dropped ownership of (or did not own) indexlet in tableId %lu, indexId %u\n",
    "Dropped ownership of (or did not own) tablet [0x%lx,0x%lx] in tableId %lu\n",
    "Dropping index '%u' from table '%lu' \n",
    "Dropping index '%u' from table '%lu'\n",
    "Dropping table %s\n",
    "Dropping table '%s' with id %lu\n",
    "Duplicate %s found during recovery. <clientID, rpcID, ackId> = <%lu, %lu, %lu>\n",
    "Duplicate RpcResult or ParticipantList found during recovery. <clientID, rpcID, ackId> = <%lu, %lu, %lu>\n",
    "Duplicated CSL entry version %lu for servers %s and %s\n",
    "EVEN_SELECTION BackupStrategy selected\n",
    "Empty Tree!\n",
    "Ending multiReadThroughput benchmark\n",
    "Ending readThroughput benchmark\n",
    "Ending writeThroughput benchmark\n",
    "Enlisted; serverId %s\n",
    "Enlisting server at %s (server id %s) supporting services: %s\n",
    "Enlisting with cooordinator\n",
    "Entry too big to append to log: %u bytes of type %d\n",
    "Entry wasn't in the list anymore; we need to handle this sensibly.\n",
    "Entry wasn't in the list anymore; we need to handle this sensibly\n",
    "Error in dumpProfile: %s\n",
    "Error invoking crashserver.py\n",
    "Error posting transmit packet: %s\n",
    "FAILURE: %s exception received fortable_id %lu\n",
    "FAILURE: %s exception received\n",
    "FAILURE: Check buffer failed\n",
    "FAILURE: Did not find new master at %s or it is not up but is still in the server list\n\n",
    "FAILURE: Dropped table %s is present\n",
    "FAILURE: Dropping table %s, %s exception received\n",
    "FAILURE: Killed master at %s in server list\n",
    "FAILURE: Server at %s is dead but is still inthe list being recovered\n",
    "FAILURE: Server at %s is in the listand is up\n",
    "FAILURE: Table %s not present\n",
    "FAILURE: Table ID at %lu should be split at key hash %lu but tabletMap does notreflect it\n",
    "FAILURE: Trying to drop table %s that does notexist. %s exception received\n",
    "FAILURE: getting Table id of %s. %s exception received\n",
    "Failed to access object (tbl %lu, obj %.*s)!\n",
    "Failed to add tablet [0x%lx,0x%lx] in tableId %lu , but no overlap found. Assuming innocuous race and sending STATUS_RETRY.\n",
    "Failed to flush the backup superblock; cannot continue safely: %s\n",
    "Failed to get time while appending to pcap file: %s\n",
    "Failed to open backup storage file %s: %s\n",
    "Failed to read metadata stored in frame %lu: %s, starting offset %lu, length %d\n",
    "Failed to read metadata stored in frame %lu: reached end of file, starting offset %lu, length %d\n",
    "Failed to read replica: %s, reading %lu bytes from backup file %lu at offset %lu.\n",
    "Failed to recover partition for recovery %lu; aborting recovery on this recovery master\n",
    "Failed to write metadata for replica: %s, writing %lu bytes to backup file %lu at offset %lu.\n",
    "Failed to write replica: %s, writing %lu bytes to backup file %lu at offset %lu.\n",
    "Failed to write the backup superblock; cannot continue safely: %s\n",
    "Failure appending to a recovery segment for a replica of <%s,%lu>\n",
    "Failure detector thread started\n",
    "Failure performing asynchronous IO (short read: wanted %lu, got %lu at offset %lu in file %lu; errno %d: %s)\n",
    "False positive for leadership loss; updating version from %u to %u\n",
    "False positive for server id %s (\"%s\")\n",
    "Fatal error in BackupFailureMonitor: %s\n",
    "Fatal error in BackupService::gcThread: %s\n",
    "Fatal error in CoordinatorServerList: %s\n",
    "Fatal error in MasterRecoveryManager: %s\n",
    "Fatal error in PriorityTaskQueue: %s\n",
    "Fatal error in cleaner thread: %s\n",
    "Fatal error in coordinator at %s: %s\n",
    "Fatal error in epollThreadMain: %s\n",
    "Fatal error in server at %s: %s\n",
    "Fatal error in workerThreadMain: %s\n",
    "Filling table with %d-byte objects\n",
    "Filling with %u objects of %u bytes each in %Zd tablets\n",
    "Finished insertions with %d overwrites per key\n",
    "Found entry that doesn't belong to the partition being migrated. Continuing to the next.\n",
    "Found entry that doesn't belong to the table being migrated. Continuing to the next.\n",
    "Found log digest in replica for segment %lu\n",
    "Found log entry before header while building recovery segments\n",
    "Found new master: %s\n",
    "Found no objects after crash recovery\n",
    "Found stored replica <%s,%lu> on backup storage in frame which was %s\n",
    "Freeing recovery state on backup for crashed master %s (recovery %lu), including %lu filtered replicas\n",
    "Freeing replica for master %s segment %lu\n",
    "Gathering metrics from %s\n",
    "Get size of unknown multi-op object\n",
    "Get version from unknown multi-op object\n",
    "GetMetricsLocatorRpc call failed with status %d\n",
    "Getting segment lists from backups and preparing them for recovery\n",
    "Given indexlet in tableId %lu, indexId %u overlaps with one or more other ranges.\n",
    "Given indexlet in tableId %lu, indexId %u to be truncated doesn't exist anymore.\n",
    "Got back [%s] len %u\n",
    "Got startReadingData for recovery %lu for crashed master %s; abandoning existing recovery %lu for that master and starting anew.\n",
    "Handling backup failure of serverId %s\n",
    "Hash table will have one entry for every %lu bytes in the log\n",
    "HashTable truncated to %lu buckets (nearest power of two)\n",
    "Haven't made progress in %us (likely just waiting for a write to roll the log head over, but could be deadlocked)\n",
    "IO control request failed. Couldn't find the mac address for ifName: %s\n",
    "Ignoring bad log module level: %s\n",
    "Ignoring bad log module name: %s\n",
    "Ignoring full server list with version %lu (server list already populated, version %lu)\n",
    "Ignoring out-of order server list update with version %lu (local server list is at version %lu)\n",
    "Ignoring replica for segment id %lu from backup %s because it's past the head segment (%lu)\n",
    "In table '%lu' I split the tablet at key %lu \n",
    "In table '%s' I split the tablet at key %lu\n",
    "Inbound migrations have been running continuously for %.0f seconds; is it possible that something is hung?\n",
    "Incoming RPC contained unknown opcode %d\n",
    "Incoming RPC contains no header (message length %d)\n",
    "Incorrect CREATE hint for \"%s\": object already exists\n",
    "Incorrect UPDATE hint for \"%s\": object doesn't exist\n",
    "Index %u for table '%lu' already exists\n",
    "Index not found for tableId %lu, indexId %u\n",
    "Indexlet migration failed: could not fit object into empty segment (obj bytes %u)\n",
    "InfRc listening on UDP: %s\n",
    "InfRcTransport aborting %s request to %s\n",
    "InfUdDriver bandwidth: %d Gbits/sec, maxTransmitQueueSize: %u bytes\n",
    "Infiniband destructor called with %lu receive buffers in use\n",
    "Infiniband receive buffers ran out (%d new requests arrived); could cause significant delays\n",
    "Infiniband receive error (%d: %s)\n",
    "Infiniband receiver temporarily ran out of packet buffers; could result in dropped packets\n",
    "Infud transmit failed: %s\n",
    "Initialized InfUdDriver buffers: %u receive buffers (%u MB), %u transmit buffers (%u MB), took %.1f ms\n",
    "Inserting index entry for tableId %lu, keyIndex %u, key %s, primaryKeyHash %lu\n",
    "Inserting: tableId %lu, indexId %u, hash %lu,\nkey: %s\n",
    "Installing indexlet %d for table %lu as part of recovery %lu (backing table id %lu, next node id %lu)\n",
    "Invalid index id %u. Secondary keys have index id greater than 0.\n",
    "Invalid tombstoneRatio argument (%f). Must be in [0, 1].\n",
    "Invoked for server %s even though either no update was sent out or it has already been invoked. Possible race/bookeeping issue.\n",
    "Just before crashing at %s:\n",
    "KILLING SERVER AT %s\n",
    "Kernel ARP cache entry for host at %s is in use! Sleeping for %d us then retry for %dth time\n",
    "Kicked off building recovery segments\n",
    "Killed server containing index\n",
    "Killing %s\n",
    "Known transports: %s\n",
    "Lease reservations are not keeping up; maxReservedLeaseId = %lu\n",
    "Load segment %lu replica from backup %s with expected load time of %lu ms\n",
    "Local Infiniband lid is %u\n",
    "Locator for InfUdDriver: %s\n",
    "LockTable contains non LOG_ENTRY_TYPE_PREP type;found %s instead\n",
    "Log write sync has taken over 10s; seems to be stuck\n",
    "LogCleaner thread started\n",
    "LogCleaner thread stopping\n",
    "Long delay waiting for transmit buffers (%.1f ms elapsed, %lu buffers now free); deadlock or target crashed?\n",
    "Long delay waiting for transmit buffers (%.1f ms elapsed, %lu buffers now free)\n",
    "Long gap in dispatcher: %.1f ms\n",
    "Long lockout in poller: %.1f ms\n",
    "Looking up: tableId %lu, indexId %u.\nfirst key: %s\n last  key: %s\n\n",
    "Lost ZooKeeper leadership; current leader info: %.*s, version: %u, our version: %u\n",
    "Lost replica(s) for segment %lu while open due to crash of backup %s\n",
    "Master client %d couldn't read from tableId %lu\n",
    "Master exiting while outstanding replication operations were still pending\n",
    "Master exiting while segment %lu had operations still pending\n",
    "Master is using %u backups\n",
    "Master reading from table %lu\n",
    "Master to allocate %lu bytes total, %lu of which are for the hash table\n",
    "Master tried to free non-existent segment: <%s,%lu>\n",
    "Master tried to open a storage frame but there are no frames free (all %lu frames are in use); rejecting\n",
    "Master tried to write replica for <%s,%lu> but another replica was recovered from storage with the same id; rejecting write request\n",
    "Master will have %lu segments and %lu lines in the hash table\n",
    "Master/backup recovery done *extremely* rough time: %.2f s\n",
    "Membership verification failed for %s\n",
    "Membership verification succeeded for %s\n",
    "Memory capacity exceeded; must delete objects before any more new objects can be created\n",
    "Memory compaction disabled, but wanted %d%% compaction!?\n",
    "Memory pinned\n",
    "Memory usage now %d MB (decreased %d MB)\n",
    "Memory usage now %d MB (increased %d MB)\n",
    "Metrics mismatches: %lu\n",
    "Metrics: %s %lu\n",
    "Metrics: begin server %s\n",
    "Migrating a partition of an indexlet in indexId %u in tableId %lu from %s (this server) to %s.\n",
    "Migrating an index entry.\n",
    "Migrating tablet [0x%lx,0x%lx] in tableId %lu to %s\n",
    "Migrating to myself doesn't make much sense.\n",
    "Migrating to myself doesn't make much sense\n",
    "Migration request for tablet this master does not own: tablet [0x%lx,0x%lx] in tableId %lu\n",
    "Migration succeeded for tablet [0x%lx,0x%lx] in tableId %lu; sent %lu objects and %lu tombstones to %s, %lu bytes in total\n",
    "Mmapped %lu-byte region from [%s] at %p\n\n",
    "Modifying indexlet map to set recovery master%s as master for %lu, %u, %lu\n",
    "Modifying tablet map to set recovery master %s as master for %lu, %lu, %lu\n",
    "Multi-read rate: %.1f kobjects/sec\n",
    "Must hold a TombstoneProtector when replaying segments\n",
    "My server ID is %s\n",
    "New queue pair for %s:%u, nonce 0x%lx (total creates %d, deletes %d)\n",
    "New runtime option working - crashing coordinator\n",
    "No cache trace events to print\n",
    "No clean segments available; deferring operations until cleaner runs\n",
    "No index entries to insert; returning\n",
    "No index entries to remove; returning\n",
    "No log digest among replicas on available backups. Will retry recovery later.\n",
    "No more servers available now\n\n",
    "No success in resolving MAC address for host at %s!\n",
    "No supported transport found for locator %s\n",
    "No tablets in crashed server %s, removing it from coordinator server list\n",
    "No time trace events to print\n",
    "No valid TableStats Estimator; using naive partitioning.\n",
    "NodeID: %lu\r\n%s\n",
    "Notifying recovery master ok to serve tablets\n",
    "Notifying replica manager of failure of serverId %s\n",
    "Null `this` pointer\n",
    "Null header; offset %u, segment length %u\n",
    "Number of times between %d and %d usecs: %d (%.2f%%)\n",
    "Objs selected.\n",
    "Old replica for <%s,%lu> has been called back into service, so won't garbage-collect it (%d more old replicas left)\n",
    "On-storage replica metadata indicates a different segment size than the backup service was told to use; ignoring the problem; note ANY call to open a segment on this backup could cause the overwrite of your strangely sized replicas.\n",
    "Opened session with coordinator at %s\n",
    "Opening <%s,%lu>\n",
    "Out of memory\n",
    "Out-of-bounds appended attempted on storage frame: offset %lu, length %lu, segmentSize %lu \n",
    "Outgoing %s RPC delayed for %.2f ms because of insufficient receive buffers\n",
    "Ownership of tablet [0x%lx,0x%lx] in tableId %lu already transfered\n",
    "Partition Scheme for Recovery:\n%s\n",
    "Performing %u inserts of %u byte objects\n",
    "Performing %u removals of objects just created\n",
    "Performing %u removals of objects just inserted\n",
    "Performing %u writes of %u byte objects\n",
    "Ping succeeded to server %s (%s) in %.1f us\n",
    "Ping timeout to server id %s (locator \"%s\")\n",
    "Pinning memory\n",
    "Pool destroyed with %lu objects still outstanding!\n",
    "PortTimeOut=%d\n",
    "Printing TabletMap\n\n",
    "Prior backup had ServerId %s\n",
    "Prior backup had cluster name '%s'\n",
    "Processor does not have SSE 4.2\n",
    "Processor has SSE 4.2\n",
    "Quiesce waiting for frame %lu to sync (isScheduled: %u)\n",
    "RAMCloud exception: %s\n\n",
    "RANDOM_REFINE_AVG BackupStrategy selected\n",
    "RANDOM_REFINE_MIN BackupStrategy selected\n",
    "RPC size (%u) does not match advertised length (%u)\n",
    "Ran out of segments without finding head\n",
    "Read object from log, nodeId = %lu, size = %d\n",
    "Read rate: %.1f kobjects/sec\n",
    "Reading all of the objects just inserted.\n",
    "Reading one of the objects just inserted\n",
    "Ready to receive indexlet in indexId %u for tableId %lu\n",
    "Ready to receive tablet [0x%lx,0x%lx] in tableId %lu from \"??\"\n",
    "Reassigning an indexlet of index id %u for table id %lu having backing table id %lu to master %s\n",
    "Reassigning table id %lu, key hashes 0x%lx-0x%lx to master %s\n",
    "Reassigning tablet [0x%lx,0x%lx] in tableId %lu from %s to %s\n",
    "Received %s response from %s with %u bytes\n",
    "Received backup write request from server %s which is not in server list version %lu:\n%s\n",
    "Received ping from server not in cluster: %s\n",
    "Receiving %u bytes of migration data for tablet [0x%lx,??] in tableId %lu\n",
    "Recovered tablet 0x%lx-0x%lx for table '%s' (id %lu) on server %s\n",
    "Recovering master %s, partition %lu, %lu replicas available\n",
    "Recovering nextNodeId.\n",
    "Recovery %lu building %d recovery segments for each replica for crashed master %s and filtering them according to the following partitions:\n%s\n",
    "Recovery %lu completed for master %s (now %lu active recoveries)\n",
    "Recovery %lu for crashed master %s is no longer needed; will clean up as next possible chance.\n",
    "Recovery complete, took %.1f ms, useful replaying time %.1f ms (%.1f%% effective)\n",
    "Recovery completed in %lu ns, failure detected in %lu ns\n",
    "Recovery failed; some objects seem to be missing\n",
    "Recovery master %s crashed while recovering a partition of server %s\n",
    "Recovery master %s failed to recover its partition for crashed server %s\n",
    "Recovery master %s got super secret partition id; killing self.\n",
    "Recovery master failed to recover master %lu partition %lu\n",
    "Recovery master reported completing recovery %lu but there is no ongoing recovery with that id; this should only happen after coordinator rollover; asking recovery master to abort this recovery\n",
    "Recovery of server %s failed to recover some tablets, rescheduling another recovery\n",
    "Recovery segment for segment %lu corrupted; trying next backup: %s\n",
    "Recovery segments already built for <%s,%lu>\n",
    "Recreated server %s at %s with services %s, status %s\n",
    "Registered %Zd bytes at %p\n",
    "Rejecting open: no free storage frames\n",
    "Reloading backup superblock (version %lu, superblockFrame %u) from previous run\n",
    "Removed server %s from replication group %lu\n",
    "Removing index entry for tableId %lu, keyIndex %u, key %s, primaryKeyHash %lu\n",
    "Removing replica for segmentId %lu from replica list for backup %s because it was open and had <id, epoch> <%lu ,%lu> which is less than the required <id, epoch> <%lu ,%lu> for the recovering master\n",
    "Removing replication group %lu (has %d members)\n",
    "Removing server %s from cluster/coordinator server list\n",
    "Removing server at %s from killedservers list. Now being reusedfor a new server\n\n",
    "Removing: tableId %lu, indexId %u, hash %lu,\nkey: %s\n",
    "Replica failed integrity check; skipping extraction of log digest: %s\n",
    "Replica information retrieved from storage: %f ms\n",
    "Replica of <%s,%lu> metadata failed integrity check; will not be used for recovery (note segment id in this log message may be corrupted as a result)\n",
    "Replicas stored on disk have a different clusterName ('%s'). Scribbling storage to ensure any stale replicas left behind by old backups aren't used by future backups\n",
    "Replicas stored on disk have matching clusterName ('%s'). Scanning storage to find all replicas and to make them available to recoveries.\n",
    "Replication factor is 0; memory compaction disabled.\n",
    "Reporting completion of recovery %lu\n",
    "Request queue for dispatch thread full, worker blocked..\n",
    "Requested recovery segment from recovery %lu, but current recovery for that master is %lu\n",
    "Requested segment <%s,%lu> is secondary, starting build of recovery segments now\n",
    "Requesting master %s to drop table id %lu indexId %u\n",
    "Requesting master %s to drop table id %lu, key hashes 0x%lx-0x%lx\n",
    "Requesting master %s to split table id %lu at key hash 0x%lx\n",
    "Requesting removal of old index entries\n",
    "Rescheduling update for server %s, version %lu, updateSequence %lu, status %s\n",
    "Resend %lu\n",
    "Reserved %u seglets for emergency head segments (%lu MB). %lu seglets (%lu MB) left in default pool.\n",
    "Reserved %u seglets for the cleaner (%lu MB). %lu seglets (%lu MB) left in default pool.\n",
    "Reserving %lu bytes of log space\n",
    "Reset requested: deleting external storage for workspace '%s'\n",
    "Resetting acked.open for segment %lu replica %lu\n",
    "Response from %s for %s RPC is too short (needed at least %d bytes, got %d)\n",
    "Retransmitting to client %s: sequence %lu, offset %u, length %u, elapsed time %.1f us\n",
    "Retransmitting to server %s: sequence %lu, offset %u, length %u, elapsed time %.1f us\n",
    "Retry exception thrown after reply sent for %s RPC\n",
    "Retrying after %s error deleting %s\n",
    "Retrying after %s error getting children of %s\n",
    "Retrying after %s error reading %s\n",
    "Retrying after %s error reading child %s\n",
    "Retrying after %s error reading children of %s for removal\n",
    "Retrying after %s error while reading %s\n",
    "Retrying after %s error while setting %s\n",
    "Retrying after %s error writing %s\n",
    "Retrying because of transaction lock\n",
    "Returning after %s error creating %s\n",
    "Returning after %s error reading %s\n",
    "Returning after %s error setting %s\n",
    "Returning invalid server id\n",
    "Returning stale time. SafeTimeUpdater may be running behind.\n",
    "Returning success.\n",
    "RouteTable contains no entry for %s interface!\n",
    "RpcWrapper::isReady found unknown state %d for %s request\n",
    "Run Complete: %f %f\n",
    "Run Complete: %f\n",
    "Running Client\n",
    "SAFEVERSION %lu discarded\n",
    "SAFEVERSION %lu recovered\n",
    "STATUS_WRONG_SERVER in %s RPC to %s\n",
    "Scheduling recovery of master %s\n",
    "Segment %lu closed (length %d)\n",
    "Segment %lu is the head of the log\n",
    "Segment %lu listed in the log digest but not found among available backups\n",
    "Segment %lu recovering from lost replica which was on backup %s\n",
    "Selecting objs.\n",
    "Sending %s request to %s with %u bytes\n",
    "Sending %u segment ids for this master (%u primary)\n",
    "Sending StartPartitioning: %s\n",
    "Sending last migration segment\n",
    "Sending migration segment\n",
    "Sending ping to server %s (%s)\n",
    "Sending response to remove RPC\n",
    "Sending response to write RPC\n",
    "Sent %lu total objects, %lu total tombstones, %lu total bytes.\n",
    "Sent %u bytes of LogDigest to coordinator\n",
    "Sent %u bytes of table statistics to coordinator\n",
    "Server %s crashed, but it had no tablets\n",
    "Server %s doesn't store <%lu, %*s>; refreshing object map\n",
    "Server %s doesn't store <%lu, 0x%lx>; refreshing object map\n",
    "Server %s doesn't store given secondary key for table %lu, index id %u; refreshing object map\n",
    "Server %s is crashed (server list version %lu)\n",
    "Server %s is now in replication group %lu\n",
    "Server %s is removed (server list version %lu)\n",
    "Server %s is up (server list version %lu)\n",
    "Server %s marked crashed; waiting for cluster to recover from its failure before freeing <%s,%lu>\n",
    "Server %s marked down; cluster has recovered from its failure; freeing replica <%s,%lu>\n",
    "Server %s marked down; cluster has recovered from its failure\n",
    "Server %s responded to a server list update but is no longer in the server list...\n",
    "Server %s returned STATUS_RETRY from %s request: %s\n",
    "Server %s returned STATUS_RETRY from %s request\n",
    "Server List from coordinator:\n%s\n",
    "Server class is not capable of running the CoordinatorService (yet).\n",
    "Server has not recovered from lost replica; retaining replica for <%s,%lu>; will probe replica status again later\n",
    "Server has recovered from lost replica; freeing replica for <%s,%lu> (%d more old replicas left)\n",
    "Server id %s has crashed, notifying the cluster and starting recovery\n",
    "Server id (%s) in index map no longer in server list; omitting locator for entry (tableName %s,tableId %lu, indexId %d)\n",
    "Server id (%s) in tablet map no longer in server list; omitting locator for entry (tableName %s, tableId %lu, startKeyHash 0x%lx)\n",
    "Server list for server %s is so far out of date that we can't fix it (its version: %lu, maxConfirmedVersion: %lu)\n",
    "Server process id: %u\n",
    "Server ran out of space while filling with test data; run your experiment again with a larger master; stored %u of %u objects before running out of space\n",
    "Server received LOG_TIME_TRACE request from client %s for sequence %lu\n",
    "Server remotely told to kill itself.\n",
    "ServerList Update Failed : %s update (%ld => %ld)\n",
    "ServerList Update Success: %s update (%ld => %ld)\n",
    "Servers started %d times, killed %d times\n",
    "Services started\n",
    "Set PortTimeout to %d (ms: -1 to disable.)\n",
    "Short write while writing the backup superblock; cannot continue safely\n",
    "SideLog finished committing (data is durable).\n",
    "Signal %d (%s) at address %p from %p\n",
    "Skipping metrics for %s; it is not up\n",
    "Skipping object with <tableId, keyHash> of <%lu,%lu> because it appears to have existed prior to this tablet's creation.\n",
    "Skipping removal for server %s: it doesn't exist\n",
    "Skipping serverCrashed for server %s: it doesn't exist\n",
    "Skipping serverCrashed for server %s: state is %s\n",
    "Slow responding to ping request from server %s; took %.2f ms\n",
    "Slow write to replica storage on device %lu: %.1f ms for %lu bytes\n",
    "Some replicas from log digest not on available backups. Will retry recovery later.\n",
    "Spinner done\n",
    "Spinner gap of %.1f us (%.2f ms since last gap, iteration %i)x\n",
    "Spinner starting\n",
    "Split and migration request for indexlet this master does not own: backing table for indexlet in indexId %u in tableId %lu.\n",
    "Split and migration request for indexlet this master does not own: indexlet in indexId %u in tableId %lu.\n",
    "Split count %d\n",
    "Split exists\n",
    "Spurious crash report on unknown server id %s\n",
    "Starting Client\n",
    "Starting backup replica garbage collector thread\n",
    "Starting backup service\n",
    "Starting getRecoveryData from %s for segment %lu on channel %ld (after RPC completion)\n",
    "Starting getRecoveryData from %s for segment %lu on channel %ld (initial round of RPCs)\n",
    "Starting multiReadThroughput benchmark\n",
    "Starting read test for %d-byte objects\n",
    "Starting readThroughput benchmark\n",
    "Starting recovery %lu for crashed master %s; recovering partition %lu (see user_data) of the following partitions:\n%s\n",
    "Starting recovery %lu for crashed server %s with %u partitions\n",
    "Starting recovery %lu for crashed server %s with index %d\n",
    "Starting recovery %lu for crashed server %s\n",
    "Starting recovery %lu on recovery master %s, partition %d\n",
    "Starting recovery of server %s (now %lu active recoveries)\n",
    "Starting replication of segment %lu replica slot %ld on backup %s\n",
    "Starting server at %s\n\n",
    "Starting services\n",
    "Starting startReadingData on backup %s\n",
    "Starting to build recovery segments for (<%s,%lu>)\n",
    "Starting write test for %d-byte objects\n",
    "Starting writeThroughput benchmark\n",
    "Storage metadata block too small to hold BackupReplicaMetadata\n",
    "Stored superblock had a bad checksum: stored checksum was %x, but stored data had checksum %x\n",
    "Stored superblock's cluster name should end in \0; this should never happen unless there is a software bug\n",
    "Strating shuffling test.\n",
    "Superblock frame %u written\n",
    "Table %s dropped\n",
    "Table %s is present\n",
    "Table ID %lu, start key hash %lu,end key hash %lu\n\n",
    "Table digest missing during recovery.\n",
    "Table recovery complete: %lu table(s)\n",
    "Tablet is currently locked for migration!\n",
    "Tablet migration failed: could not fit object into empty segment (obj bytes %u)\n",
    "Task destroyed while RPC active: segment %lu, server %s\n",
    "TcpTransport connected to itself %s\n",
    "TcpTransport couldn't connect to %s: %s\n",
    "TcpTransport couldn't create listen socket: %s\n",
    "TcpTransport couldn't listen on socket: %s\n",
    "TcpTransport couldn't open socket for session: %s\n",
    "TcpTransport couldn't set SO_REUSEADDR on listen socket: %s\n",
    "TcpTransport couldn't set nonblocking on listen socket: %s\n",
    "TcpTransport failed to get client socket info\n",
    "TcpTransport received oversize message (%d bytes); discarding extra bytes\n",
    "TcpTransport recv error: %s\n",
    "TcpTransport sendmsg error: %s\n",
    "The data in the Lambda exceeds %lu bytes, aborting...\n",
    "The interface name %s is too long.\n",
    "The parsed line from routeFile has %zu line however we expect 11 fields in standard Linux Kernel's routeFile!\n",
    "Time exceeded: stopping test after %d measurements\n",
    "Told recovery master %s to kill itself\n",
    "Told to take ownership of tablet [0x%lx,0x%lx] in tableId %lu, but already own [0x%lx,0x%lx]. Returning success.\n",
    "Tombstone cleanup complete\n",
    "Took %lu ms to filter %lu primary replicas\n",
    "Took ownership of existing tablet [0x%lx,0x%lx] in tableId %lu in RECOVERING state\n",
    "Took ownership of indexlet in tableId %lu indexId %u\n",
    "Took ownership of new tablet [0x%lx,0x%lx] in tableId %lu\n",
    "Transaction %lu.%lu consisting of %u operation(s) aborted after %.1f us because the commit took longer than expected.\n",
    "Transaction %lu.%lu detected TxPrepare trying to ABORT after COMMITTED.\n",
    "Transaction %lu.%lu found TxPrepare claiming to have COMMITTED after ABORT already received.\n",
    "Transmit buffer with %u bytes pending for lid %u, opcode %s\n",
    "Transmit buffers unavailable for %.1f seconds; deadlock or target crashed?\n",
    "Transmit failed for buffer %lu: destination lid %u, status %s, opcode %s\n",
    "Tried to append to a frame but it was already enqueued for load for recovery; calling master is probabaly already dead\n",
    "Tried to append to a frame but it was already enqueued for load for recovery; calling master is probably already dead\n",
    "Tried to append to a frame but it wasn't open on this backup; this can happen legitimately if a master's rpc system retried a closing write rpc.\n",
    "Tried to append to a frame but it wasn'topen on this backup\n",
    "Tried to append to a frame with metadata of length %lu but storage only allows max length of %d\n",
    "Tried to close a frame but it was already enqueued for load for recovery; calling master is probably already dead\n",
    "Tried to ping locator \"%s\", but id %s was stale\n",
    "Tried to send UDP packet with %d bytes but only %d bytes was sent!\n",
    "Tried write to a replica of segment <%s,%lu> but no such replica was open on this backup (server id %s)\n",
    "Trying to commit. %zu objs selected.\n",
    "TxID <%lu,%lu> was acked but not all prepared operations have been decided.\n",
    "TxPrepare fail. Key: %.*s, object is already locked\n",
    "TxPrepare fail. Type: %d Key: %.*s, RejectRule outcome: %s rejectRule.givenVersion %lu currentVersion %lu\n",
    "TxPrepare(readOnly) fail. Key: %.*s, object is already locked\n",
    "TxPrepare(readOnly) fail. Type: %d Key: %.*s, RejectRule outcome: %s rejectRule.givenVersion %lu currentVersion %lu\n",
    "UdpDriver bandwidth: %d Gbits/sec, maxTransmitQueueSize: %u bytes\n",
    "UdpDriver error receiving from socket: %s\n",
    "UdpDriver error sending to socket: %s\n",
    "UdpDriver using port %d\n",
    "Unable to initiate transaction recovery for TxId (%lu, %lu) because participant list record could not be found; BUG; transaction timeout timer may have started without first being registered.\n",
    "Unable to recover segment %lu\n",
    "Unexpected ClientException during recovery: %s\n",
    "Unexpected RPC from %s to %s creates potential for deadlock; must update 'callees' table in scripts/genLevels.py\n",
    "Unexpected exception '%s' after committing transaction %lu.%lu.\n",
    "Unexpected exception '%s' while issuing decisions for transaction %lu.%lu; likely recoverable.\n",
    "Unexpected exception '%s' while preparing to commit transaction %lu.%lu; will result in internal error.\n",
    "Unexpected exception '%s' while transaction %lu.%lu was in an invalid state; this case should not be reachable.\n",
    "Unexpected exception during recovery: %s\n",
    "Unexpected high-order bits set in SerializedServiceMask being deserialized which do not correspond to a valid ServiceType; ignoring the extra bits; you might want to check your code closely; something is wrong.\n",
    "Unexpected result from TxPrepare in transaction %lu.%lu.\n",
    "Unexpected status '%s' while processingbatched Transaction::ReadOp.\n",
    "Unexpected transaction decision value in transaction %lu.%lu.\n",
    "Unexpectedly short write to metadata for replica, file 0 at offset %lu, expected length %lu, actual write length %lu\n",
    "Unexpectedly short write to replica, file %lu at offset %lu, expected length %lu, actual write length %lu\n",
    "Unfinished RPCs are preventing %d segments from being freed (segment epoch %lu, RPC epoch %lu, current epoch %lu, stuck for %.0f seconds)\n",
    "Unimplemented multiOp (type = %u) received!\n",
    "Unknown LogEntry (id=%u)\n",
    "Unknown balancer specified: \"%s\"\n",
    "Unknown event type %d\n",
    "Unknown fatal error in BackupFailureMonitor.\n",
    "Unknown fatal error in BackupService::gcThread.\n",
    "Unknown fatal error in CoordinatorServerList.\n",
    "Unknown fatal error in MasterRecoveryManager.\n",
    "Unknown fatal error in PriorityTaskQueue.\n",
    "Unknown fatal error in coordinator at %s\n",
    "Unknown fatal error in epollThreadMain.\n",
    "Unknown fatal error in server at %s\n",
    "Unknown fatal error in workerThreadMain.\n",
    "Unknown indexlet in tableId %lu, indexId %u\n",
    "Unknown indexlet: tableId %lu, indexId %u, hash %lu,\nkey: %s\n",
    "Unknown status for tablet\n",
    "Unknown status stored in tablet map\n",
    "Unknown transaction op type found for CacheEntry (%lu : %lu) while attempting to prepare transaction %lu.%lu.\n",
    "Unknown workload type %s - Using default\n",
    "Unsafe use of base class schedule, use schedule(Lock&, Priority)\n",
    "Updating replicationEpoch to %lu,%lu on coordinator to ensure lost replicas will not be reused\n",
    "User of this ServerTracker did not NULL out previous pointer for server %s\n",
    "Using %u backups\n",
    "Using /dev/null to \"store\" your data. I hope you know what you're doing!\n",
    "Using fixed balancer with %u%% disk cleaning\n",
    "Using the fillWithTestData rpc on the master with key <1,'0'>\n",
    "Using tombstone ratio balancer with ratio = %f\n",
    "Verification took %lu ns\n",
    "Verified host failure: id %s (\"%s\")\n",
    "Verifying all data.\n",
    "Verifying objects\n",
    "Waiting for %s (ping failed)\n",
    "Waiting for %s (ping succeeded)\n",
    "Waiting for recovery to complete on recovery masters\n",
    "Waiting for response of RPC with id: %ld\n",
    "Waiting on recovery data for segment %lu from %s\n",
    "While committing transaction, lock already released when it should not be. Key: %.*s PrepareRef: %lu\n",
    "While preparing transaction, lock already acquired after checking lock was free. Key: %.*s\n",
    "Will enlist as a replacement for formerly crashed server %s which left replicas behind on disk\n",
    "WorkerTimer stalled waiting for handler to complete; perhaps destructor was invoked from handler?\n",
    "Write rate for %.2f second interval: %6.2f kops/sec\n",
    "Write rate: %.1f kobjects/sec\n",
    "Write requested for closed replica <%s,%lu>; treating the request as noop\n",
    "Writing key(nodeId) is %lu, size of node = %d\n",
    "Wrote value into table\n",
    "ZooKeeper API error: %s\n",
    "ZooKeeper close failed: %s\n",
    "ZooKeeper connection closed\n",
    "ZooKeeper connection didn't reach open state; retrying\n",
    "ZooKeeper connection opened with %s\n",
    "ZooKeeper connection reached bad state (%s) during open\n",
    "ZooKeeper error (%s): reopening connection\n",
    "ZooKeeper node name \"%s\" contains no slashes\n",
    "\n%s\n",
    "aborting %s RPC to server %s, sequence %lu: timeout\n",
    "accounting error for live bytes in segment: entry type %lu, entryLengths[i] %u, deadEntryLengths %u\n",
    "activate() on qp in state %d\n",
    "all tablets now normal\n",
    "avg insert took %.1f usec\n",
    "avg insert took %lu ticks\n",
    "avg read took %lu ticks, %lu nano seconds\n",
    "avg write took %lu ticks, %lu nano seconds\n",
    "bad ParticipantList checksum! (leaseId: %lu, txId: %lu)\n",
    "bad TxDecisionRecord checksum! leaseId: %lu\n",
    "bad nonce from %s (expected 0x%016lx, got 0x%016lx, port %d); ignoring\n",
    "bad object checksum! key: %s, version: %lu\n",
    "bad objectSafeVer checksum! version: %lu\n",
    "bad preparedOp checksum! key: %s, leaseId: %lu, rpcId: %lu\n",
    "bad preparedOpTombstone checksum! tableId: %lu, keyHash: %lu, leaseId: %lu, rpcId: %lu\n",
    "bad tombstone checksum! key: %s, version: %lu\n",
    "buffer has consumed %u bytes of extra storage, current allocation: %d bytes\n",
    "buffer too small to hold header (length = %u)\n",
    "cannot remove more objects than I create!\n",
    "client acked unfinished RPC with rpcId <%lu>\n",
    "client: Connecting to %s\n",
    "connected to %s via local port %d\n",
    "coordinator replication epoch for %s updated to %lu,%lu\n",
    "coordinator: Listening on %s\n",
    "corrupt packet (data length %d, packet length %d\n",
    "corrupted data: expected %u bytes, found %u bytes\n",
    "corrupted data: expected '%c', got '%c' (\"%s%.*s%s\" vs \"%s%.*s%s\")\n",
    "couldn't bind port for clientSetupSocket: %s\n",
    "couldn't find \"coordinatorClusterClock\" object in external storage; starting new clock from zero; benign if starting new cluster from scratch, may cause linearizability failures otherwise\n",
    "couldn't find \"coordinatorUpdateManager\" object in external storage; starting new cluster from scratch\n",
    "couldn't get port for clientSetupSocket: %s\n",
    "couldn't munmap undesirable mapping!\n",
    "couldn't open log file '%s': %s\n",
    "couldn't verify server id for %s: connection failed\n",
    "create+open table took %lu ticks\n",
    "dispatch thread not keeping up with UdpDriver packet reader\n",
    "dropTabletOwnership skipped for master %s (table %lu, index %u) because server isn't running\n",
    "dropTabletOwnership skipped for master %s (table %lu, key hashes 0x%lx-0x%lx) because server isn't running\n",
    "enlisting server %s claims to replace server id %s, which is still in the server list; taking its word for it and assuming the old server has failed\n",
    "epoll_wait failed in Dispatch::epollThread: %s\n",
    "epoll_wait returned no events in Dispatch::epollThread\n",
    "error in TcpTransport::AcceptHandler accepting connection for '%s': %s\n",
    "failed to bind socket for port %s: %s\n",
    "failed to bind to mac address\n",
    "failed to create client socket: %s\n",
    "failed to create receive completion queue\n",
    "failed to create server socket: %s\n",
    "failed to create transmit completion queue\n",
    "failed to exchange with server (%s) within allotted %u microseconds (sent request %u times, local port %d)\n",
    "failed to find infiniband device: %s\n",
    "failed to find qp_num %ud in serverPortMap\n",
    "failed to find qp_num in map\n",
    "failed to open infiniband device: %s\n",
    "failed to receive rpc!\n",
    "failed to transition to INIT state errno %d\n",
    "failed to transition to RTR state\n",
    "failed to transition to RTS state\n",
    "fcntl F_GETFL failed: %s\n",
    "fcntl F_SETFL failed: %s\n",
    "finished with %s\n",
    "found %d masters, %d backups (in %d servers)\n",
    "found indexlet and changed its server id to %s\n",
    "futexWait failed in WorkerManager::workerMain: %s\n",
    "futexWake failed in Worker::handoff: %s\n",
    "gave up waiting for all outstanding transmissions after 1ms\n",
    "getRecoveryData complete\n",
    "getRecoveryData failed on %s for segment %lu, trying next backup; failure was: %s\n",
    "getRecoveryData masterId %s, segmentId %lu, partitionId %lu\n",
    "getsockname returned error: %s\n",
    "ibv_close_device failed\n",
    "ibv_create_qp failed (%d prior creates, %d deletes)\n",
    "ibv_dealloc_pd failed\n",
    "ibv_poll_cq failed: %d\n",
    "ibv_query_port failed on port %u\n\n",
    "ibv_reg_mr failed to register %Zd bytes at %p\n",
    "ibv_reg_mr failed to register %lu bytes at %p\n",
    "incoming data doesn't match active RPC (nonce 0x%016lx); perhaps RPC was cancelled?\n",
    "initializing CoordinatorClusterClock: startingClusterTime = %lu\n",
    "initializing CoordinatorUpdateManager: lastFinished = %lu, firstAvailable = %lu\n",
    "initializing TableManager: nextTableId = %lu\n",
    "invalid digest checksum (computed 0x%08x, expect 0x%08x\n",
    "invalid offset (%u) and/or length (%u); segment has %lu seglets, total length %lu, currentOffset %u\n",
    "length left not even 64-bit multiple (%u)\n",
    "migration data received for tablet not in the RECOVERING state (state = %d)!\n",
    "migration data received for unknown tablet [0x%lx,??] in tableId %lu\n",
    "missing required option --coordinator\n",
    "munmap of large block failed with %d\n",
    "need >= 20 byte objects to do verification!\n",
    "not found indexlet, which is an error\n",
    "number of overwrite is less than 1! No data can be written\n",
    "packet from %s too short (%u bytes)\n",
    "packet of type %s from %s too short (%u bytes)\n",
    "plumb() on qp in state %d\n",
    "pointer out of range; p: %p, blockBase: 0x%lu, length: %lu\n",
    "pollCompletionQueue failed with result %d\n",
    "posix_memalign returned %s\n",
    "read took %lu ticks, %lu nano seconds\n",
    "read took %lu ticks\n",
    "received impossibly short packet: %d bytes\n",
    "recovered value read from %s has length %u (expected %u)\n",
    "recovered value read from %s has length %u\n",
    "recoveryComplete failed on %s, ignoring; failure was: %s\n",
    "recoveryComplete failed on %s, ignoring; server no longer in the servers list\n",
    "recvfrom failed: %s\n",
    "recvfrom got a strange incoming size: %Zd\n",
    "recvfrom returned bad length (%Zd) while receiving from ip: [%s] port: [%d]\n",
    "recvfrom returned error %d: %s\n",
    "renewLease: Lost ZooKeeper leadership; leader object %s no longer exists\n",
    "replicationEpoch ok, lost open replica recovery complete on segment %lu\n",
    "requesting retry of %s request (master disable count %d)\n",
    "retrying server id check for %s: server not yet enlisted\n",
    "sched_getaffinitity failed: %s\n",
    "sched_setaffinitity failed: %s\n",
    "segment corrupt: bad checksum (expected 0x%08x, was 0x%08x)\n",
    "segment corrupt: entries run off past allocated segment size (segment size %lu, next entry would have started at %u)\n",
    "segment corrupt: entries run off past expected length (expected %u, next entry would have started at %u)\n",
    "sendto failed, len = %Zd\n",
    "sendto returned bad length (%Zd) while sending to ip: [%s] port: [%d]\n",
    "sendto returned error %d: %s\n",
    "server %s considered crashed: no response to %s RPC\n",
    "server for locator %s has incorrect id (expected %s, got %s); discarding session\n",
    "server no longer in cluster; committing suicide\n",
    "server: Couldn't pin to core %d: %s\n",
    "set indexlet %lu to locator %s, id %s\n",
    "set tablet %lu %lu %lu to locator %s, id %s\n",
    "setMasterRecoveryInfo for server %s to %s\n",
    "setMasterRecoveryInfo server doesn't exist: %s\n",
    "slave %d is done.\n",
    "split point for %lu at %lu\n",
    "splitMasterTablet skipped for master %s (table %lu, split key hash 0x%lx) because server isn't running\n",
    "startPartition failed on %s, failure was: %s\n",
    "startReadingData failed on %s, failure was: %s\n",
    "starting to connect to %s via local port %d, nonce 0x%lx\n",
    "tablet down\n",
    "takeIndexletOwnership failed during indexlet reassignment for master %s (indexlet of index id %u for table id %lu) because server isn't running\n",
    "takeIndexletOwnership skipped for master %s (table %lu, index %u) because server isn't running\n",
    "takeTabletOwnership failed during tablet reassignment for master %s (table %lu, key hashes 0x%lx-0x%lx) because server isn't running\n",
    "takeTabletOwnership skipped for master %s (table %lu, key hashes 0x%lx-0x%lx) because server isn't running\n",
    "time expired after %d iterations\n",
    "timed out waiting for response from %s; retrying\n",
    "timestamp > now\n",
    "totalAddressHandleAllocCalls: %lu (count)\n",
    "totalAddressHandleAllocTime: %lu (ticks)\n",
    "txCount++\n",
    "unexpected GRANT from client %s, id (%lu,%lu), grantOffset %u\n",
    "unexpected opcode %s received from client %s\n",
    "unexpected opcode %s received from server %s\n",
    "unknown ServerStatus %d\n",
    "unknown command %s\n",
    "unknown exception\n",
    "verify not supported with fillWithTestData\n",
    "verifying cluster membership for %s\n",
    "version number mismatch in update for server %s: completed update has version %lu, but first version from entry is %lu\n",
    "want %d/%d active masters/backups, but found %d/%d (in %d servers)\n",
    "wc.status != IBV_WC_SUCCESS; is %d\n",
    "wc.status(%d:%s) != IBV_WC_SUCCESS\n",
    "worker: %s\n",
    "worker\n",
    "write rate for %d-byte objects: %.1f kobjects/sec, %.1f MB/sec\n",
    "write took %lu ticks\n"
};

// Number of log statements in the array above
int numRAMCloudLogs = sizeof(RAMCloudLogs)/sizeof(std::string);